/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminportalRouteRouteImport } from './routes/adminportal/route'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminportalIndexRouteImport } from './routes/adminportal/index'
import { Route as AdminportalIdRouteImport } from './routes/adminportal/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminportalRouteRoute = AdminportalRouteRouteImport.update({
  id: '/adminportal',
  path: '/adminportal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminportalIndexRoute = AdminportalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminportalRouteRoute,
} as any)
const AdminportalIdRoute = AdminportalIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminportalRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adminportal': typeof AdminportalRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/adminportal/$id': typeof AdminportalIdRoute
  '/adminportal/': typeof AdminportalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/adminportal/$id': typeof AdminportalIdRoute
  '/adminportal': typeof AdminportalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adminportal': typeof AdminportalRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/adminportal/$id': typeof AdminportalIdRoute
  '/adminportal/': typeof AdminportalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adminportal'
    | '/admin'
    | '/apply'
    | '/login'
    | '/adminportal/$id'
    | '/adminportal/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/login'
    | '/adminportal/$id'
    | '/adminportal'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/adminportal'
    | '/admin'
    | '/apply'
    | '/login'
    | '/adminportal/$id'
    | '/adminportal/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminportalRouteRoute: typeof AdminportalRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminportal': {
      id: '/adminportal'
      path: '/adminportal'
      fullPath: '/adminportal'
      preLoaderRoute: typeof AdminportalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminportal/': {
      id: '/adminportal/'
      path: '/'
      fullPath: '/adminportal/'
      preLoaderRoute: typeof AdminportalIndexRouteImport
      parentRoute: typeof AdminportalRouteRoute
    }
    '/adminportal/$id': {
      id: '/adminportal/$id'
      path: '/$id'
      fullPath: '/adminportal/$id'
      preLoaderRoute: typeof AdminportalIdRouteImport
      parentRoute: typeof AdminportalRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminportalRouteRouteChildren {
  AdminportalIdRoute: typeof AdminportalIdRoute
  AdminportalIndexRoute: typeof AdminportalIndexRoute
}

const AdminportalRouteRouteChildren: AdminportalRouteRouteChildren = {
  AdminportalIdRoute: AdminportalIdRoute,
  AdminportalIndexRoute: AdminportalIndexRoute,
}

const AdminportalRouteRouteWithChildren =
  AdminportalRouteRoute._addFileChildren(AdminportalRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminportalRouteRoute: AdminportalRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
